;******************************************************************************
;   Filename:	    Proyecto3 -> principal.asm
;   Date:		    12/11/2020
;   File Version:	    v.1
;   Author:		    Noel Prado
;   Company:	    UVG
;   Description:	    proyecto 3
;
;*******************************************************************************  

#include "p16f887.inc"

; CONFIG1
; __config 0xE0D5
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

  GPR_VAR UDATA
 
 W_TEMP RES 1
 STATUS_TEMP RES 1
 FSR_TEMP RES 1

 CANAL0 RES 1
 CANAL1 RES 1
 CANAL2 RES 1
 CONTROL_ADC RES 1 
 AJUSTE_PWM RES 1
 TIMING1 RES 1 
 TIMING2 RES 1 
 CONTROL_ONDA RES 1 
 CONTROL_TX RES 1 
 VALOR_CENTENAS_BOCA RES 1
 VALOR_DECENAS_BOCA  RES 1
 VALOR_UNIDADES_BOCA RES  1
 VALOR_CENTENAS_CEJA1 RES 1
 VALOR_DECENAS_CEJA1  RES 1
 VALOR_UNIDADES_CEJA1 RES  1
 VALOR_CENTENAS_CEJA2 RES 1
 VALOR_DECENAS_CEJA2  RES 1
 VALOR_UNIDADES_CEJA2 RES  1
 VALOR_BIN RES 1
 VALOR_CENTENAS RES 1
 VALOR_DECENAS  RES 1
 VALOR_UNIDADES RES  1
 DEL		RES 1

 
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED
ISR_VECT    CODE 0x0004
    
PUSH:
    MOVWF   W_TEMP
    SWAPF   STATUS,W
    MOVWF   STATUS_TEMP
    SWAPF   FSR,W
    MOVWF  FSR_TEMP

INT_TMR0:
    BTFSS   INTCON,T0IF
    GOTO    INT_ADC
    BCF	INTCON,T0IF
    
     MOVLW   .0
    SUBWF   CONTROL_ONDA, W
    BTFSC  STATUS, Z 
    GOTO ONDA_INICIA
    
    MOVLW   .1
    SUBWF   CONTROL_ONDA, W
    BTFSC  STATUS, Z 
    GOTO ONDA1
    
    MOVLW   .2
    SUBWF   CONTROL_ONDA, W
    BTFSC  STATUS, Z 
    GOTO ONDA2
    
    ONDA_INICIA ;EN LA PRIMERA FASE SE COLOCA EN 1 EL PIN RC0 Y RC3 SE ENCUENTRA EN 0
    BSF	PORTC, RC0 ;SE COLOCA EN 1
    MOVF    TIMING1,W 
    CLRF	TMR0
    SUBWF   TMR0,F  ;TMRO =  256 - TRABAJO1
    INCF    CONTROL_ONDA,F ;A LA SIGUIENTE ENTRADA SE EJECUTA PWM1
    GOTO INT_ADC
    
    ONDA1
    BCF	PORTC,RC0 ;AL PASAR EL TIEMPO ESTABLECIDO POR LA VARIABLE TRABAJO 1
    BSF	PORTC, RC3
    MOVF   TIMING2,W
    CLRF TMR0
    SUBWF   TMR0,F ;256 - TRABAJO2
    INCF CONTROL_ONDA,F
    GOTO INT_ADC
    
    ONDA2
    BCF	PORTC,RC0
    BCF	PORTC,RC3
    CLRF	TMR0 ;LA SIGUIENTE INTERRUPCION OCURRIRA DENTRO DE 4.09mS
    CLRF CONTROL_ONDA
    
INT_ADC:
    BTFSS   PIR1, ADIF 
    GOTO    POP ;SI NO ESTA ACTIVA SE SALE
    
    BCF	PIR1, ADIF
    MOVLW   .0
    SUBWF   CONTROL_ADC, W
    BTFSC  STATUS, Z 
    GOTO RT_ADC0
    
    MOVLW   .1
    SUBWF   CONTROL_ADC, W
    BTFSC  STATUS, Z 
    GOTO RT_ADC1
    
    MOVLW   .2
    SUBWF   CONTROL_ADC, W
    BTFSC  STATUS, Z 
    GOTO RT_ADC2
    
    CLRF    CONTROL_ADC
    RT_ADC0
    MOVF    ADRESH, W
    MOVWF   CANAL0
    BCF	ADCON0,CHS1
    BSF	ADCON0,CHS0 ;SE SELECCIONA EL CANAL 1
    GOTO FIN
    
    RT_ADC1
    MOVF    ADRESH, W
    MOVWF   CANAL1
    BSF	ADCON0,CHS1
    BCF	ADCON0,CHS0 ;SE SELECCIONA EL CANAL 2
    GOTO FIN
   
    RT_ADC2
    MOVF    ADRESH,W
    MOVWF   CANAL2
    BCF	ADCON0,CHS1
    BCF	ADCON0,CHS0 ;SE SELECCIONA EL CANAL 0
    GOTO FIN
    
    FIN
    INCF    CONTROL_ADC,F
    BSF	ADCON0,GO ;INICIA CONVERSION
    
POP:
    SWAPF   STATUS_TEMP,W
    MOVWF   STATUS
    SWAPF   FSR_TEMP,W
    MOVWF   FSR
    SWAPF   W_TEMP,F
    SWAPF   W_TEMP,W
    RETFIE
    
SEND_DATA:
    BTFSS   PIR1,TXIF ;SI NO ESTA OCUPADO SE SALTA EL RETURN
    RETURN
   
    ;----- SE DETERMINA QUE DATO HAY QUE ENVIAR -------------------------------
    
    MOVLW   .0
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    PRIMERO
    
    MOVLW   .1
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    SEGUNDO
    
    MOVLW   .2
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    TERCERO
    
    MOVLW   .3
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    COMA
    
    MOVLW   .4
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    CUARTO
    
    MOVLW   .5
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    QUINTO
    
    MOVLW   .6
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    SEXTO
    
    MOVLW   .7
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    COMA
    
    MOVLW   .8
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    SEPTIMO
    
    MOVLW   .9
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    OCTAVO
    
    MOVLW   .10
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    NOVENO
    
    MOVLW   .11
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    GOTO    FINAL
    
    MOVLW   .12
    SUBWF CONTROL_TX, W
    BTFSC   STATUS, Z
    CLRF    CONTROL_TX

    PRIMERO
    MOVF    VALOR_CENTENAS_BOCA,W
    GOTO ENVIAR
    
    SEGUNDO
    MOVF VALOR_DECENAS_BOCA,W
    GOTO ENVIAR
    
    TERCERO
    MOVF VALOR_UNIDADES_BOCA,W
    GOTO ENVIAR
    
    CUARTO
    MOVF    VALOR_CENTENAS_CEJA1,W
    GOTO ENVIAR
    
    QUINTO
    MOVF VALOR_DECENAS_CEJA1,W
    GOTO ENVIAR
    
    SEXTO
    MOVF VALOR_UNIDADES_CEJA1,W
    GOTO ENVIAR
    
    SEPTIMO
    MOVF    VALOR_CENTENAS_CEJA2,W
    GOTO ENVIAR
    
    OCTAVO
    MOVF VALOR_DECENAS_CEJA2,W
    GOTO ENVIAR
    
    NOVENO
    MOVF VALOR_UNIDADES_CEJA2,W
    GOTO ENVIAR
    
    COMA
    MOVLW   .44 ;COMA EN ASCII
    GOTO    ENVIAR_SIN_SUMA
    
    FINAL
    MOVLW   .10 ;SALTO DE LINEA
    GOTO    ENVIAR_SIN_SUMA
    
    ENVIAR
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    ENVIAR_SIN_SUMA
    MOVWF   TXREG
    INCF    CONTROL_TX,F
    RETURN
    
    
MAIN_PROG CODE                      ; let linker place main program
 
 START
    
 CALL	CONFIG_IO
    
LOOP:
    CALL    DELAY
    
    MOVLW   CANAL0
    MOVWF   FSR 
     CALL    TRANSFORMADA
    MOVF    AJUSTE_PWM,W
    MOVWF   CCPR1L
    
    MOVLW    CANAL1
    MOVWF   FSR
    CALL    TRANSFORMADA
    MOVF    AJUSTE_PWM
    MOVWF   CCPR2L
    
    MOVLW   CANAL2
    MOVWF   FSR
    CALL   TRANSFORMADA
    MOVF    AJUSTE_PWM,W
    MOVWF TIMING1
    

    ;******************************** CONVERSION A BINARIO CODIFICADO A DECIMAL**************************
    MOVF    CANAL0,W
    MOVWF   VALOR_BIN
    MOVLW   VALOR_CENTENAS_BOCA
    MOVWF   FSR
   CALL CONVERTIR
   
    MOVF    CANAL1,W
    MOVWF   VALOR_BIN
    MOVLW   VALOR_CENTENAS_CEJA1
    MOVWF   FSR
   CALL CONVERTIR
   
    MOVF    CANAL2,W
    MOVWF   VALOR_BIN
    MOVLW   VALOR_CENTENAS_CEJA2
    MOVWF   FSR
   CALL CONVERTIR
   
   
   CALL SEND_DATA
   
    GOTO LOOP    
    
    
CONVERTIR:
    CLRF    VALOR_CENTENAS
    CLRF    VALOR_DECENAS
    CLRF    VALOR_UNIDADES
    
    CENTENAS
    MOVLW   .100
    SUBWF   VALOR_BIN,W    
    BTFSS   STATUS, C	
    GOTO    DECENAS 
    INCF    VALOR_CENTENAS,F
    MOVWF   VALOR_BIN
    GOTO CENTENAS
    
    DECENAS
    MOVLW   .10
    SUBWF   VALOR_BIN,W
    BTFSS   STATUS,C  
    GOTO UNIDADES
    INCF    VALOR_DECENAS,F
    MOVWF   VALOR_BIN
    GOTO DECENAS
    
    UNIDADES
    MOVLW .1
    SUBWF   VALOR_BIN,W
    BTFSS   STATUS,C 
    GOTO    GUARDAR
    INCF    VALOR_UNIDADES,F
    MOVWF VALOR_BIN
    GOTO UNIDADES
    
    GUARDAR
    MOVF    VALOR_CENTENAS,W 
    MOVWF   INDF
    
    INCF    FSR,F
    MOVF    VALOR_DECENAS,W
    MOVWF   INDF
    
    INCF    FSR,F
    MOVF   VALOR_UNIDADES,W
    MOVWF   INDF
    RETURN
    
    
TRANSFORMADA
    BCF	STATUS,C
    RRF	INDF, W 
    ADDLW   .31 
   MOVWF    AJUSTE_PWM 
   RETURN
   
   
   CONFIG_IO
    BCF	STATUS, IRP ;BANCO 2 Y 3 EN EL DIRECCIONAMIENTO INDIRECTO
    CLRF    CANAL0
    CLRF    CANAL1
    CLRF    CANAL2
    CLRF    CONTROL_ADC
    CLRF    CONTROL_ONDA
    CLRF    CONTROL_TX
    
    BANKSEL ANSEL
    
    MOVLW B'00001111'
    MOVWF ANSEL
    CLRF    ANSELH 
    
    BCF	OPTION_REG, T0CS 
    BCF	OPTION_REG, PSA 
    BCF	OPTION_REG, PS2
    BSF	OPTION_REG,PS1
    BSF	OPTION_REG,PS0 
    
    BANKSEL TRISA
    MOVLW   .255
    MOVWF   TRISA
    CLRF	   TRISC
    CLRF	   TRISD
    
    BSF	INTCON,GIE 
    BSF	INTCON, PEIE
  
    
    BSF	PIE1, ADIE 
    BSF	PIE1, RCIE 

    MOVLW .255 
    MOVWF  PR2 
    CLRF    ADCON1 
     BCF	TXSTA,TX9
     BSF	TXSTA, TXEN
     BCF	TXSTA, SYNC
     BSF	TXSTA, BRGH
     
    MOVLW   .25 
    MOVWF   SPBRG
    
    BCF	STATUS,RP0 
    
    BSF	RCSTA, SPEN
    BCF	RCSTA, RX9
    BSF	RCSTA, CREN

 
    
    BCF	INTCON, T0IF
    CLRF	TMR0
    BSF	INTCON, T0IE
    
    
    BANKSEL  CCP1CON
    BCF	CCP1CON, 7
    BCF	CCP1CON, 6

    BCF	CCP1CON, 5
    BCF	CCP1CON, 4
    BSF	CCP1CON, 3
    BSF	CCP1CON, 2
    BCF	CCP1CON, 1
    BCF	CCP1CON, 0
    
    BANKSEL  CCP1CON 
    BCF	CCP2CON, 7
    BCF	CCP2CON, 6
    BCF	CCP2CON, 5
    BCF	CCP2CON, 4
    BSF	CCP2CON, 3
    BSF	CCP2CON, 2
    BCF	CCP2CON, 1  
    BCF	CCP2CON, 1
    BCF	CCP2CON, 0
   
    
    BCF	T2CON, 6
    BCF	T2CON, 5
    BCF	T2CON, 4
    BCF	T2CON, 3    
    BCF	T2CON, 2
    BSF	T2CON, 1
    BSF	T2CON, 0
    BSF	T2CON, TMR2ON
    
    MOVLW   B'01000001' 
    MOVWF   ADCON0
    

    BSF	ADCON0, GO
   
   RETURN
   
    
 DELAY
    MOVLW   .255
    MOVWF   DEL
    DECFSZ  DEL, F
    GOTO    $-1
    RETURN
    
    END